# This is a basic workflow to help you get started with Actions

name: cron-news

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  schedule:
    - cron: '00 */3 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Watermelon HTTP client
        # You may pin to the exact commit or the version.
        # uses: CamiloGarciaLaRotta/watermelon-http-client@054c532cb02e9bd533ba3579cf03f8c332061713
        uses: CamiloGarciaLaRotta/watermelon-http-client@v1.5
        with:
          # Endpoint to query
          # optional, default is https://api.github.com
          url: 3.35.143.195:3000/api/news
          # HTTP method
          method: get
